
package serverhoroscopo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerHoroscopo", targetNamespace = "http://ServerHoroscopo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerHoroscopo {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHoroscopo", targetNamespace = "http://ServerHoroscopo/", className = "serverhoroscopo.GetHoroscopo")
    @ResponseWrapper(localName = "getHoroscopoResponse", targetNamespace = "http://ServerHoroscopo/", className = "serverhoroscopo.GetHoroscopoResponse")
    @Action(input = "http://ServerHoroscopo/ServerHoroscopo/getHoroscopoRequest", output = "http://ServerHoroscopo/ServerHoroscopo/getHoroscopoResponse")
    public String getHoroscopo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
