
package serverhoroscopo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerHoroscopoImpService", targetNamespace = "http://ServerHoroscopo/", wsdlLocation = "http://localhost:10000/ws/Horoscopo?wsdl")
public class ServerHoroscopoImpService
    extends Service
{

    private final static URL SERVERHOROSCOPOIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERHOROSCOPOIMPSERVICE_EXCEPTION;
    private final static QName SERVERHOROSCOPOIMPSERVICE_QNAME = new QName("http://ServerHoroscopo/", "ServerHoroscopoImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10000/ws/Horoscopo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERHOROSCOPOIMPSERVICE_WSDL_LOCATION = url;
        SERVERHOROSCOPOIMPSERVICE_EXCEPTION = e;
    }

    public ServerHoroscopoImpService() {
        super(__getWsdlLocation(), SERVERHOROSCOPOIMPSERVICE_QNAME);
    }

    public ServerHoroscopoImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERHOROSCOPOIMPSERVICE_QNAME, features);
    }

    public ServerHoroscopoImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVERHOROSCOPOIMPSERVICE_QNAME);
    }

    public ServerHoroscopoImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERHOROSCOPOIMPSERVICE_QNAME, features);
    }

    public ServerHoroscopoImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerHoroscopoImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerHoroscopo
     */
    @WebEndpoint(name = "ServerHoroscopoImpPort")
    public ServerHoroscopo getServerHoroscopoImpPort() {
        return super.getPort(new QName("http://ServerHoroscopo/", "ServerHoroscopoImpPort"), ServerHoroscopo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerHoroscopo
     */
    @WebEndpoint(name = "ServerHoroscopoImpPort")
    public ServerHoroscopo getServerHoroscopoImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServerHoroscopo/", "ServerHoroscopoImpPort"), ServerHoroscopo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERHOROSCOPOIMPSERVICE_EXCEPTION!= null) {
            throw SERVERHOROSCOPOIMPSERVICE_EXCEPTION;
        }
        return SERVERHOROSCOPOIMPSERVICE_WSDL_LOCATION;
    }

}
