
package servercentral;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerCentral", targetNamespace = "http://ServerCentral/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerCentral {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws MalformedURLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPronostico", targetNamespace = "http://ServerCentral/", className = "servercentral.GetPronostico")
    @ResponseWrapper(localName = "getPronosticoResponse", targetNamespace = "http://ServerCentral/", className = "servercentral.GetPronosticoResponse")
    @Action(input = "http://ServerCentral/ServerCentral/getPronosticoRequest", output = "http://ServerCentral/ServerCentral/getPronosticoResponse", fault = {
        @FaultAction(className = MalformedURLException_Exception.class, value = "http://ServerCentral/ServerCentral/getPronostico/Fault/MalformedURLException")
    })
    public List<String> getPronostico(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws MalformedURLException_Exception
    ;

}
