
package serverclima;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerClimaImpService", targetNamespace = "http://ServerClima/", wsdlLocation = "http://localhost:10001/ws/Clima?wsdl")
public class ServerClimaImpService
    extends Service
{

    private final static URL SERVERCLIMAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERCLIMAIMPSERVICE_EXCEPTION;
    private final static QName SERVERCLIMAIMPSERVICE_QNAME = new QName("http://ServerClima/", "ServerClimaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10001/ws/Clima?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERCLIMAIMPSERVICE_WSDL_LOCATION = url;
        SERVERCLIMAIMPSERVICE_EXCEPTION = e;
    }

    public ServerClimaImpService() {
        super(__getWsdlLocation(), SERVERCLIMAIMPSERVICE_QNAME);
    }

    public ServerClimaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERCLIMAIMPSERVICE_QNAME, features);
    }

    public ServerClimaImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVERCLIMAIMPSERVICE_QNAME);
    }

    public ServerClimaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERCLIMAIMPSERVICE_QNAME, features);
    }

    public ServerClimaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerClimaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerClima
     */
    @WebEndpoint(name = "ServerClimaImpPort")
    public ServerClima getServerClimaImpPort() {
        return super.getPort(new QName("http://ServerClima/", "ServerClimaImpPort"), ServerClima.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerClima
     */
    @WebEndpoint(name = "ServerClimaImpPort")
    public ServerClima getServerClimaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServerClima/", "ServerClimaImpPort"), ServerClima.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERCLIMAIMPSERVICE_EXCEPTION!= null) {
            throw SERVERCLIMAIMPSERVICE_EXCEPTION;
        }
        return SERVERCLIMAIMPSERVICE_WSDL_LOCATION;
    }

}
